language: rust

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

services:
  - docker  

# Save up the cargo build cache
cache: cargo  

before_install:
- rustup component add rustfmt

# cargo test
rust:
  - stable
  - beta
jobs:
  fast_finish: true

# Build Test Fmt
script: ./scripts/build.sh

# Running deb build scripts
script: ./rustscan-debbuilder/run.sh

# Add in the github release details here
deploy:
  provider: releases
  api_key: $GH_0AUTH_TOKEN
  file: target/debug/rustscan
  file: debs/*.deb
  skip_cleanup: true
  on:
    tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
